"""Regenerate backend/data/openings.tsv from the lichess chess-openings dataset.

Source: https://github.com/lichess-org/chess-openings (CC0 public domain).
That repo publishes a.tsv-e.tsv with columns eco/name/pgn, where pgn is SAN.
We convert each line to a UCI move sequence once, here, so the backend never
parses SAN at runtime.

    python backend/tools/build_openings.py            # download from GitHub
    python backend/tools/build_openings.py --src DIR  # use local a.tsv-e.tsv

Regenerate the data file with this script rather than editing it by hand.
"""

import argparse
import csv
import io
import os
import sys
import urllib.request

import chess
import chess.pgn

SOURCE_URL = ("https://raw.githubusercontent.com/lichess-org/"
              "chess-openings/master/{letter}.tsv")
FILES = ("a", "b", "c", "d", "e")
OUT_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "data", "openings.tsv")


def _read_source(letter, src_dir):
    if src_dir:
        with open(os.path.join(src_dir, f"{letter}.tsv"), encoding="utf-8") as fh:
            return fh.read()
    with urllib.request.urlopen(SOURCE_URL.format(letter=letter), timeout=60) as resp:
        return resp.read().decode("utf-8")


def _to_uci(pgn):
    """SAN movetext -> space-joined UCI, or None when it will not replay."""
    game = chess.pgn.read_game(io.StringIO(pgn))
    if game is None:
        return None
    board = game.board()
    ucis = []
    for move in game.mainline_moves():
        if not board.is_legal(move):
            return None
        ucis.append(move.uci())
        board.push(move)
    return " ".join(ucis) or None


def build(src_dir=None, out_path=OUT_PATH):
    rows = {}
    skipped = 0
    for letter in FILES:
        reader = csv.DictReader(io.StringIO(_read_source(letter, src_dir)),
                                delimiter="\t")
        for row in reader:
            uci = _to_uci(row["pgn"])
            if uci is None:
                skipped += 1
                continue
            rows[uci] = (row["eco"], row["name"])

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Generated by backend/tools/build_openings.py -- do not edit.\n")
        fh.write("# Source: lichess-org/chess-openings (CC0 public domain).\n")
        fh.write("uci\teco\tname\n")
        for uci in sorted(rows):
            eco, name = rows[uci]
            fh.write(f"{uci}\t{eco}\t{name}\n")

    depths = [len(uci.split(" ")) for uci in rows]
    print(f"wrote {out_path}")
    print(f"  lines={len(rows)} skipped={skipped} "
          f"max_depth={max(depths)} plies "
          f"size={os.path.getsize(out_path) / 1024:.0f} KiB")
    return len(rows)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", help="directory holding local a.tsv-e.tsv")
    parser.add_argument("--out", default=OUT_PATH)
    args = parser.parse_args(argv)
    build(args.src, args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
